[build]
  command = "netlify-lambda build endpoints/"
  functions = "functions"
[template.environment]
  API_KEY="Set your API key"
  CORS_WHITELIST="Optional comma-separated list of allowed cross-origin domains"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"